# Generated by Django 5.2.3 on 2025-07-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('cliente', 'Cliente')], max_length=20)),
                ('setor', models.CharField(blank=True, choices=[('financeiro', 'Financeiro'), ('ti', 'TI'), ('rh', 'Recursos Humanos'), ('compras', 'Compras')], max_length=20, null=True)),
            ],
        ),
    ]
