# Generated by Django 5.2.3 on 2025-07-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico'), ('funcionario', 'Funcionário')], max_length=20),
        ),
    ]
