# Generated by Django 5.2.3 on 2025-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.CharField(blank=True, choices=[('financeiro', 'Financeiro'), ('ti', 'TI'), ('rh', 'Recursos Humanos'), ('compras', 'Compras'), ('presidade', 'Presidente'), ('vice-presidente', 'Vice Precidente'), ('ouvidoria', 'Ouvidoria')], max_length=20, null=True),
        ),
    ]
