# Generated by Django 5.2.3 on 2025-07-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='titulo',
        ),
    ]
