# Generated by Django 5.2.3 on 2025-07-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_remove_chamado_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data_fechamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Critica')], default='media', max_length=20),
        ),
    ]
