# Generated by Django 5.2.3 on 2025-07-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_alter_chamado_data_abertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
