# Generated by Django 5.2.3 on 2025-07-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0004_alter_chamado_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='data_abertura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
