# Generated by Django 5.2.3 on 2025-08-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0005_alter_chamado_data_abertura'),
        ('usuario', '0003_alter_usuario_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_chamados', to='usuario.usuario')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='chamado.chamado')),
            ],
        ),
    ]
