# Generated by Django 5.2.3 on 2025-08-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0006_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
