# Generated by Django 5.2.3 on 2025-08-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0011_alter_chamado_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
    ]
