# Generated by Django 5.2.3 on 2025-09-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0013_alter_chamado_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'ordering': ['-data_abertura']},
        ),
    ]
