# Generated by Django 5.2.3 on 2025-08-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historico',
            old_name='status_anterior',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='historico',
            name='status_novo',
        ),
        migrations.AlterField(
            model_name='historico',
            name='data_alteracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
