# Generated by Django 5.2.3 on 2025-07-02 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numero_patrimonio', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('notebook', 'Notebooks'), ('monitores', 'Monitores'), ('estabilizadores', 'Estabilizadores'), ('teclados', 'Teclados'), ('mouses', 'Mouse'), ('impressoras', 'Impressoras')], default='notebook', max_length=50)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('manutencao', 'Manutenção'), ('descartado', 'Descartado')], default='ativo', max_length=40)),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setor.setor')),
            ],
        ),
    ]
