# Generated by Django 5.2.3 on 2025-07-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('notebook', 'Notebooks'), ('monitores', 'Monitores'), ('estabilizadores', 'Estabilizadores'), ('teclados', 'Teclados'), ('mouses', 'Mouse'), ('impressoras', 'Impressoras'), ('switch', 'Switch')], default='notebook', max_length=50),
        ),
    ]
