# Generated by Django 5.2.3 on 2025-07-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0002_alter_equipamento_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='numero_patrimonio',
            new_name='patrimonio',
        ),
    ]
