# Generated by Django 5.2.3 on 2025-07-27 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_rename_numero_patrimonio_equipamento_patrimonio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='tipo',
        ),
    ]
