# Generated by Django 5.2.3 on 2025-07-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='chamado',
        ),
    ]
