# Generated by Django 5.2.3 on 2025-07-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_rename_autor_comentario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
